import { Doctor, Service } from "./types";

export const CLINIC_INFO = {
  name: "Amulyam Dental Studio",
  tagline: "Precision Care for Beautiful, Confident Smiles",
  phone: "+91 92036 04211",
  rawPhone: "+919203604211",
  email: "amulyamdentalstudio@gmail.com",
  address: "Plot-17, 2nd Floor, Koushlya Nagar, BDA Road, Awadhpuri, Bhopal, Madhya Pradesh 462022, India",
  shortAddress: "Plot-17, 2nd Floor, Awadhpuri, Bhopal, MP",
  hours: "Mon to Sat: 10:00 AM – 8:00 PM (Emergency 24/7 on call)",
  workingHours: "9:00 AM – 10:00 PM",
  mapsUrl: "https://maps.google.com/?q=Amulyam+Dental+Studio+BDA+Road+Awadhpuri+Bhopal",
  whatsappUrl: "https://wa.link/kkyo2t",
  socials: {
    instagram: "https://www.instagram.com/amulyamdentalstudio/?hl=en",
    facebook: "https://www.facebook.com/profile.php?id=61588570899576",
    whatsapp: "https://wa.link/kkyo2t",
  },
  stats: {
    happyPatients: "1,200+",
    teethWhitened: "850+",
    dentalImplants: "450+",
    yearsExperience: "5+",
    googleRating: "5.0",
    reviewCount: "140+",
  },
};

export const LEAD_DOCTOR: Doctor = {
  name: "Dr. Shreya Nidhi",
  role: "Lead Dentist & Implant Specialist",
  qualifications: "BDS, MDS (Cosmetic & Restorative)",
  experience: "5+ Years",
  specialization: "Comprehensive Dentistry & Smile Design",
  bio: "With a passion for creating radiant, healthy smiles, Dr. Shreya Nidhi brings world-class dental expertise and a compassionate chairside manner to Amulyam Dental Studio. Dedicated to painless dentistry and state-of-the-art restorative procedures, she personalizes every treatment to each patient's unique lifestyle.",
  image: "/images/dr_shreya_.jpg",
  achievements: [
    "5+ Years Clinical Excellence in Advanced Implantology",
    "Specialized Certification in Invisible Aligners & Smile Design",
    "Painless Rotary Endodontics Specialist",
    "Over 1,200+ Successful Smile Transformations in Bhopal",
  ],
};

export const CLINIC_SERVICES: Service[] = [
  {
    id: "rct",
    title: "Root Canal Treatment (RCT)",
    category: "Endodontics",
    tagline: "Painless Relief & Natural Tooth Preservation",
    description: "Removes infected pulp, relieves severe dental pain, and preserves your natural tooth structure using advanced rotary endodontics.",
    longDescription: "Our modern root canal therapy is virtually painless and performed with state-of-the-art rotary instruments and apex locators, ensuring maximum precision and rapid healing in just 1-2 visits.",
    duration: "45 - 60 mins",
    priceEstimate: "Starting from ₹2,500",
    isPopular: true,
    image: "/images/s3.jpg",
    benefits: [
      "100% painless procedure with gentle local anesthesia",
      "Saves natural tooth and prevents jaw bone degradation",
      "Digital RVG x-ray guidance for accurate canal cleaning",
      "Long-lasting porcelain/zirconia crown placement",
    ],
    faqs: [
      { question: "Is RCT painful?", answer: "Not at all. With modern local anesthesia and rotary tech, RCT feels as comfortable as getting a standard filling." },
      { question: "How many sittings are required?", answer: "Most standard cases are completed in a single sitting or 2 short visits." },
    ],
  },
  {
    id: "dental-implants",
    title: "Dental Implants",
    category: "Implantology",
    tagline: "Permanent, Natural-Looking Tooth Replacement",
    description: "The gold standard permanent solution for missing teeth with 100% natural chewing strength, look, and feel.",
    longDescription: "Titanium biocompatible fixtures anchored into the jawbone provide unmatched stability for crowns, bridges, and full-arch prostheses.",
    duration: "60 mins per fixture",
    priceEstimate: "Starting from ₹18,000",
    isPopular: true,
    image: "/images/s2.jpg",
    benefits: [
      "Permanent lifetime tooth replacement solution",
      "Prevents facial sagging and jawbone loss",
      "Eat, chew, and speak with complete confidence",
      "Zero impact on adjacent natural teeth",
    ],
  },
  {
    id: "scaling-polishing",
    title: "Scaling & Polishing",
    category: "Preventive",
    tagline: "Deep Plaque Removal & Gum Health Care",
    description: "Removes stubborn calculus, tartar, and surface stains to refresh breath and prevent gingivitis.",
    duration: "30 - 45 mins",
    priceEstimate: "Starting from ₹800",
    isPopular: true,
    image: "/images/s8.jpg",
    benefits: [
      "Eliminates bad breath and bleeding gums",
      "Ultrasonic gentle scaling with zero enamel erosion",
      "High-gloss polish for immediate stain removal",
      "Recommended every 6 months for optimal hygiene",
    ],
  },
  {
    id: "teeth-whitening",
    title: "Teeth Whitening (Bleaching)",
    category: "Cosmetic",
    tagline: "Instant Radiance up to 6 Shades Brighter",
    description: "Professional in-office laser whitening designed to remove deep tea, coffee, and tobacco stains safely.",
    duration: "45 mins",
    priceEstimate: "Starting from ₹3,500",
    isPopular: true,
    image: "/images/s9.jpg",
    benefits: [
      "Noticeable results in a single 45-minute sitting",
      "Enamel-safe pH-balanced whitening gel",
      "Custom desensitizing paste for zero sensitivity",
      "Long-lasting shine with basic home care",
    ],
  },
  {
    id: "smile-design",
    title: "Smile Design & Veneers",
    category: "Cosmetic",
    tagline: "Bespoke Aesthetic Transformations",
    description: "Enhances smile symmetry, tooth proportions, color, and harmony using modern digital smile design and porcelain veneers.",
    duration: "Custom plan",
    priceEstimate: "Consultation Required",
    isPopular: true,
    image: "/images/s14.jpg",
    benefits: [
      "Digital mock-up preview before treatment begins",
      "Ultra-thin cosmetic porcelain veneers",
      "Corrects gaps, chipped edges, and discoloration",
      "Custom tailored to your facial aesthetics",
    ],
  },
  {
    id: "aligners",
    title: "Clear Aligners",
    category: "Orthodontics",
    tagline: "Virtually Invisible Teeth Straightening",
    description: "Comfortable, removable, and clear aligners that straighten teeth without metal brackets or wires.",
    duration: "6 - 18 months plan",
    priceEstimate: "Custom 3D Plan",
    isPopular: true,
    image: "/images/s13.jpg",
    benefits: [
      "100% discreet and virtually invisible",
      "Eat your favourite foods with zero dietary limits",
      "Custom 3D treatment simulation",
      "Fewer clinic visits compared to metal braces",
    ],
  },
  {
    id: "braces",
    title: "Orthodontic Braces",
    category: "Orthodontics",
    tagline: "Precision Alignment for All Ages",
    description: "High-grade ceramic and metallic braces to correct crooked teeth, severe bite misalignments, and overcrowding.",
    duration: "12 - 24 months",
    priceEstimate: "Flexible EMI Available",
    isPopular: false,
    image: "/images/s12.jpg",
    benefits: [
      "Reliable correction for complex bite misalignments",
      "Options for aesthetic tooth-colored ceramic brackets",
      "Improves chewing efficiency and long-term oral posture",
    ],
  },
  {
    id: "crowns-bridges",
    title: "Crowns & Bridges",
    category: "Restorative",
    tagline: "Durable Ceramic & Zirconia Restorations",
    description: "Custom crafted crowns to protect root-treated or fractured teeth and fixed bridges to bridge gaps seamlessly.",
    duration: "2 visits",
    priceEstimate: "Starting from ₹3,000",
    isPopular: false,
    image: "/images/s10.jpg",
    benefits: [
      "CAD/CAM high-precision zirconia and porcelain",
      "Natural translucency matching your adjacent teeth",
      "10 to 15-year warranty options",
    ],
  },
  {
    id: "tooth-extraction",
    title: "Tooth Extraction & Wisdom Teeth",
    category: "Surgery",
    tagline: "Gentle, Safe Surgical & Routine Extractions",
    description: "Gentle removal of severely impacted wisdom teeth or non-restorable teeth under comfortable local anesthesia.",
    duration: "30 - 60 mins",
    priceEstimate: "Starting from ₹1,000",
    isPopular: false,
    image: "/images/s11.jpg",
    benefits: [
      "Painless atraumatic extraction techniques",
      "Rapid post-op healing protocol and pain management",
      "Minimal downtime and swelling control",
    ],
  },
  {
    id: "complete-denture",
    title: "Complete & Partial Dentures (RPD)",
    category: "Prosthodontics",
    tagline: "Comfortable Full Mouth Prosthetics",
    description: "Lightweight flexible dentures and full-arch acrylic prostheses crafted for snug fit and comfortable chewing.",
    duration: "3 - 4 visits",
    priceEstimate: "Custom Quote",
    isPopular: false,
    image: "/images/1.jpeg",
    benefits: [
      "Custom contoured for natural gumline fit",
      "Restores facial contour and speech clarity",
      "High impact acrylic and flexible BPS options",
    ],
  },
  {
    id: "diagnostic-xray",
    title: "Digital RVG & OPG Diagnostic X-Rays",
    category: "Diagnostic",
    tagline: "Ultra-Low Radiation 3D Digital Imaging",
    description: "High-definition instant digital radiographs providing precision visualization of bone, roots, and hidden pathologies.",
    duration: "5 mins",
    priceEstimate: "Included with checkup",
    isPopular: false,
    image: "/images/4.jpeg",
    benefits: [
      "90% less radiation than conventional film X-rays",
      "Instant high-res chairside screen visualization",
      "Accurate root canal length and bone density mapping",
    ],
  },
];

export const TIME_SLOTS = [
  "10:00 AM",
  "10:45 AM",
  "11:30 AM",
  "12:15 PM",
  "01:00 PM",
  "02:30 PM",
  "03:15 PM",
  "04:00 PM",
  "04:45 PM",
  "05:30 PM",
  "06:15 PM",
  "07:00 PM",
  "07:30 PM",
];

export const PATIENT_TESTIMONIALS = [
  {
    name: "Priya Sharma",
    role: "Patient (Smile Makeover)",
    comment: "Excellent dental care and a very friendly team. The clinic is modern, spotlessly clean, and my treatment was completely painless. Dr. Shreya explained every step clearly!",
    rating: 5,
    tag: "Root Canal & Crown",
  },
  {
    name: "Rahul Verma",
    role: "Patient (Dental Implant)",
    comment: "Highly professional doctors. They explained everything clearly and made me feel completely at ease throughout the entire implant procedure. Chewing is effortless again!",
    rating: 5,
    tag: "Dental Implant",
  },
  {
    name: "Anjali Patel",
    role: "Patient (Teeth Whitening)",
    comment: "Best dental clinic experience in Bhopal! Extremely hygienic environment, advanced digital equipment, and warm staff. My teeth are noticeably brighter in just one sitting!",
    rating: 5,
    tag: "Laser Teeth Whitening",
  },
  {
    name: "Vikram Singh",
    role: "Patient (Clear Aligners)",
    comment: "Started my clear aligners journey with Dr. Shreya. The 3D scan and custom plan were amazing. The team is always responsive on WhatsApp for questions.",
    rating: 5,
    tag: "Invisible Aligners",
  },
];

export const GALLERY_ITEMS = [
  {
    id: "clinic-1",
    title: "Modern Operatory Room & Treatment Chair",
    category: "Clinic",
    image: "/images/clinic_1.png",
    fallback: "/images/clinic_3.png",
    description: "Ergonomic dental chair with intraoral camera and digital screen display.",
  },
  {
    id: "clinic-2",
    title: "Ultra-Hygienic Sterilization Bay",
    category: "Equipment",
    image: "/images/clinic_2.png",
    fallback: "/images/clinic_4.png",
    description: "Class-B autoclave and 5-tier instrument sterilization protocol.",
  },
  {
    id: "clinic-3",
    title: "Patient Consultation Lounge",
    category: "Clinic",
    image: "/images/clinic_3.png",
    description: "Welcoming reception and calm consultation atmosphere designed to eliminate dental anxiety.",
  },
  {
    id: "clinic-4",
    title: "Advanced Dental Imaging Suite",
    category: "Technology",
    image: "/images/clinic_4.png",
    description: "Low-radiation digital RVG sensor and panoramic imaging setup.",
  },
  {
    id: "clinic-5",
    title: "Smile Design & Cosmetic Studio",
    category: "Clinic",
    image: "/images/clinic_5.png",
    description: "High-magnification surgical loupes and cosmetic shade matching studio.",
  },
];

export const BEFORE_AFTER_CASES = [
  {
    title: "Full Arch Aesthetic Smile Makeover",
    treatment: "Cosmetic Veneers & Whitening",
    duration: "2 Appointments",
    beforeText: "Discolored & uneven edges",
    afterText: "Bright, symmetrical confident smile",
    image: "/images/s14.jpg",
  },
  {
    title: "Molar Restoration with Zirconia Crown",
    treatment: "Painless RCT + CAD/CAM Crown",
    duration: "Single Sitting",
    beforeText: "Deep decay and severe pain",
    afterText: "Reinforced permanent crown",
    image: "/images/s3.jpg",
  },
];
