import {
  getAllBookings,
  createBooking,
  getBookedSlotsForDate,
  getUserByEmail,
  createUser
} from "@/lib/db";
import {
  generatePatientConfirmationEmail,
  generateAdminNewBookingAlertEmail,
  sendEmailNotification
} from "@/lib/email";
import { CLINIC_INFO, CLINIC_SERVICES, TIME_SLOTS, LEAD_DOCTOR } from "@/lib/constants";
import { Booking } from "@/lib/types";

export interface ClinicInfo {
  name: string;
  doctor: string;
  specialization: string;
  address: string;
  city: string;
  phone: string;
  email: string;
  hours: string;
  services: string[];
}

export async function getClinicInfo() {
  return {
    success: true,
    data: {
      name: CLINIC_INFO.name,
      doctor: LEAD_DOCTOR.name,
      specialization: LEAD_DOCTOR.specialization,
      address: CLINIC_INFO.address,
      city: "Bhopal, Madhya Pradesh",
      phone: CLINIC_INFO.phone,
      email: CLINIC_INFO.email,
      hours: CLINIC_INFO.hours,
      services: CLINIC_SERVICES.map((s) => `${s.title} (${s.priceEstimate})`)
    }
  };
}

export async function getAvailableSlots(date: string) {
  if (!date) {
    const today = new Date().toISOString().split("T")[0];
    date = today;
  }

  const bookedSlots = getBookedSlotsForDate(date);
  const slotsStatus = TIME_SLOTS.map((slot) => ({
    time: slot,
    available: !bookedSlots.includes(slot),
    status: bookedSlots.includes(slot) ? "Booked" : "Available"
  }));

  const availableCount = slotsStatus.filter((s) => s.available).length;

  return {
    success: true,
    date,
    totalSlots: TIME_SLOTS.length,
    availableSlotsCount: availableCount,
    slots: slotsStatus
  };
}

export async function getTreatmentPricing(query?: string) {
  let filtered = CLINIC_SERVICES;
  if (query) {
    const q = query.toLowerCase();
    filtered = CLINIC_SERVICES.filter(
      (s) =>
        s.title.toLowerCase().includes(q) ||
        s.description.toLowerCase().includes(q) ||
        q.includes(s.title.toLowerCase())
    );
  }
  return {
    success: true,
    treatments: (filtered.length > 0 ? filtered : CLINIC_SERVICES).map((s) => ({
      id: s.id,
      name: s.title,
      priceEstimate: s.priceEstimate,
      duration: s.duration,
      description: s.description
    }))
  };
}

export async function bookAppointmentTool(params: {
  patientName: string;
  patientEmail: string;
  patientPhone: string;
  serviceName: string;
  appointmentDate: string;
  appointmentTime: string;
  notes?: string;
}) {
  const {
    patientName,
    patientEmail,
    patientPhone,
    serviceName,
    appointmentDate,
    appointmentTime,
    notes = "Booked via Amulyam AI Care Concierge"
  } = params;

  if (!patientName || !patientEmail || !patientPhone || !appointmentDate || !appointmentTime) {
    return {
      success: false,
      error: "Missing required fields. Please provide name, email, phone, appointment date, and time slot."
    };
  }

  // 1. Conflict Collision Check
  const bookedSlots = getBookedSlotsForDate(appointmentDate);
  if (bookedSlots.includes(appointmentTime)) {
    const availableSlots = TIME_SLOTS.filter((s) => !bookedSlots.includes(s));
    return {
      success: false,
      conflict: true,
      error: `The slot '${appointmentTime}' on ${appointmentDate} is already reserved.`,
      alternativeSlots: availableSlots
    };
  }

  // 2. Identify or Match Service
  const matchedService = CLINIC_SERVICES.find(
    (s) => s.title.toLowerCase() === serviceName.toLowerCase()
  ) || CLINIC_SERVICES.find((s) => s.title.toLowerCase().includes(serviceName.toLowerCase())) || CLINIC_SERVICES[0];

  // 3. Check or Create Patient User
  let patientUser = getUserByEmail(patientEmail);
  if (!patientUser) {
    try {
      patientUser = createUser({
        name: patientName,
        email: patientEmail,
        phone: patientPhone,
        password: "autogenerated_ai_patient",
        role: "patient"
      });
    } catch (e) {}
  }

  // 4. Create Confirmed Booking in Database
  const booking = createBooking({
    patientName,
    patientEmail,
    patientPhone,
    serviceId: matchedService.id,
    serviceName: matchedService.title,
    category: matchedService.category,
    preferredDoctor: LEAD_DOCTOR.name,
    appointmentDate,
    timeSlot: appointmentTime,
    notes,
    userId: patientUser?.id
  });

  // 5. Automated Multi-Channel Email Dispatches
  try {
    const patientEmailData = generatePatientConfirmationEmail(booking);
    sendEmailNotification({
      to: booking.patientEmail,
      subject: patientEmailData.subject,
      html: patientEmailData.html
    }).catch(console.error);

    const adminEmailData = generateAdminNewBookingAlertEmail(booking);
    sendEmailNotification({
      to: process.env.ADMIN_ALERT_EMAIL || "amulyamdentalstudio@gmail.com",
      subject: adminEmailData.subject,
      html: adminEmailData.html
    }).catch(console.error);
  } catch (emailErr) {
    console.error("Non-fatal email dispatch error in AI bookAppointmentTool:", emailErr);
  }

  const baseUrl = process.env.NEXT_PUBLIC_APP_URL || "https://amulyam.thewebvale.com";
  const passUrl = `${baseUrl}/booking-confirmation/${booking.refNumber}`;

  return {
    success: true,
    message: "Appointment confirmed successfully!",
    appointment: {
      id: booking.refNumber,
      patientName: booking.patientName,
      patientEmail: booking.patientEmail,
      patientPhone: booking.patientPhone,
      service: matchedService.title,
      date: booking.appointmentDate,
      timeSlot: booking.timeSlot,
      status: booking.status,
      passUrl
    }
  };
}

export async function trackAppointmentTool(query: string) {
  if (!query) {
    return { success: false, error: "Please provide an Appointment Reference Number, email, or phone." };
  }

  const clean = query.trim().toLowerCase();
  const allBookings = getAllBookings();

  const match = allBookings.find(
    (b: Booking) =>
      b.refNumber.toLowerCase() === clean ||
      b.patientEmail.toLowerCase() === clean ||
      b.patientPhone.replace(/\D/g, "").includes(clean.replace(/\D/g, ""))
  );

  if (!match) {
    return {
      success: false,
      found: false,
      message: `No active booking found matching '${query}'.`
    };
  }

  const baseUrl = process.env.NEXT_PUBLIC_APP_URL || "https://amulyam.thewebvale.com";
  return {
    success: true,
    found: true,
    appointment: {
      id: match.refNumber,
      patientName: match.patientName,
      service: match.serviceName,
      date: match.appointmentDate,
      time: match.timeSlot,
      status: match.status,
      passUrl: `${baseUrl}/booking-confirmation/${match.refNumber}`
    }
  };
}
